### ISSUE TITLE
Remove pre commit lint hook

### ISSUE THREAD

**Issue by marsidev** [midudev/password-generator#146]
Currently when we commit some changes, husky try to lint all the project:

![image](https://user-images.githubusercontent.com/56328053/193658270-79390bb5-48ed-4877-8484-ed3354a0194c.png)

This can modify the code of different participants if them are not linted properly.

I suggest remove this hook, or, customize it to only lint/modify the user code (if possible).

**Comment by javierscode** [comment]
It would be great to just lint the staged files with lint-staged package: https://github.com/okonet/lint-staged

**Comment by alfredogonzalezmartinez** [comment]
I did a PR (#193) to fix that
