### ISSUE TITLE
Mi pull request fue excluido del hacktoberfest 😢

### ISSUE THREAD

**Issue by luisfalconmx** [midudev/password-generator#153]
Acabo de revisar en la pagina del hacktoberfest si mi contribución fue valida y lamentablemente no lo fue.
Al parecer las contribuciones a este repositorio no van a ser validas para el hacktoberfest. Aun asi me siento feliz de haber participado, fue una gran experiencia 😃 

![image](https://user-images.githubusercontent.com/57654255/193676734-2bf9fb0c-9581-4b8c-9463-6532571d1288.png)

**Comment by diloes** [comment]
Así es. Midudev a enviado un correo a la organización para ver si se puede solucionar. Si no, ya tiene pensado otra cosa.

**Comment by midudev** [comment]
Todavía no me han contestado, pero al parecer este año no permiten crear repositorios que estén pensados para participar en la Hacktoberfest. Cuando me contesten, os cuento a ver.

**Comment by LcsGrz** [comment]
> Todavía no me han contestado, pero al parecer este año no permiten crear repositorios que estén pensados para participar en la Hacktoberfest. Cuando me contesten, os cuento a ver.

Por donde vamos a ver las novedades?

**Comment by midudev** [comment]
Lo vamos comentando en directos de Twitch y en Discord.

Igualmente, tendremos otros premios a los que participen.

**Comment by johnsi15** [comment]
Me pueden regalar el link del Discord porfa, gracias.

**Comment by leflores-fisi** [comment]
> Me pueden regalar el link del Discord porfa, gracias.

https://discord.gg/midudev @johnsi15
