### ISSUE TITLE
Conflicto entre diferentes estilos @zerok1986

### ISSUE THREAD

**Issue by carlosfernandezcabrero** [midudev/password-generator#236]
Buenos dias 👋,

@zerok1986 tengo un problema con este estilo que has definido en tu App.css, concretamente para el elemento h1. Adjunto el estilo:

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/56631428/194078295-42987a08-0cee-4d25-a27c-b340095f4f5c.png">

Mi problema es que está entrando en conflicto para los que he definido yo para mi h1 de forma no global. Adjunto evidencias:

<img width="1588" alt="image" src="https://user-images.githubusercontent.com/56631428/194078594-b1fe0d73-0eaa-48a8-8930-da52f9d18c61.png">

Por favor, ¿Podrias arreglarlo? Te doy algunas ideas aunque seguramente que haya mejores !!!

- Encerrar tu contenido en un div con tu id de GitHub para que no aplique a otros códigos.
- Hacer referencia al h1 a través de un Id único.
- Utilizar CSS modules

Un saludo, muchas gracias

**Comment by zerok1986** [comment]
Hola @carlosfernandezcabrero. Este problema ya está solucionado. Creo que te debe faltar hacerte un pull para traerte los ultimos cambios a tu local, ya que los cambios están hechos y mergeados. Mi hoja de estilos ya no apunta al h1 sino a una ID específica creada con mi nick ('zerok1986-title').

Un saludo,

**Comment by carlosfernandezcabrero** [comment]
Muchas gracias, perfecto y mil perdones que se me paso sincronizar mi repo con el de midu. 🙌😁
