### ISSUE TITLE
Principiante en apuros con Vue.js

### ISSUE THREAD

**Issue by DyLaNHurtado** [midudev/password-generator#240]
Hola buenas 👋,
Para este reto me he atrevido a probar Vuejs 💪 y estoy un poco perdido 😵. 

He estado investigando todo lo que he podido sobre un problema que tengo pero aun no he encontrado la solución. 

Espero que aparezca alguien con más experiencia con Vue para decirme lo que estoy haciendo mal. 

Mi problema es el siguiente: 

Yo tengo este componente creado para lo del range/slider que te indicará el numero de caracteres de la contraseña. 

![imagen](https://user-images.githubusercontent.com/90937483/194098129-d4a78b08-a541-4b6f-894f-1ed6fa94bea5.png)

```vue
<template>
	<span class="flex justify-center items-center text-3xl">Length:</span> 
		<div class="flex justify-between w-full">
			<input v-model="value" type="range" class="w-5/6" :min="min" :max="max"/>
			<span class="text-center text-3xl p-4 bg-cyan-500 rounded-full aspect-square">{{value}}</span>
		</div>
</template>
<script>
	export default{
		name:'Length',
		data(){
			return{
				value: 0,min: 0, max: 100,}		
		}
}
</script>
<style>

</style>
```

La cosa es que si yo muevo el input, el valor no se actualiza, aun que tengo puesto lo del v-model. No estoy seguro si me faltaria algo pero he estado investigando un par de dias y no doy con ello.

![imagen](https://user-images.githubusercontent.com/90937483/194098644-f3a2e5da-97d0-4da5-a105-07f307aa608a.png)

Muchas gracias de antemano 👍.

**Comment by marcelotk15** [comment]
I see no errors in your code.
Some error show in console?

**Comment by DyLaNHurtado** [comment]
Efectivamente @midudev  por si a alguien más le pasa era eso.  Ya va perfectamente! ☺️. Muchas gracias a los dos por contestarme tan pronto.

![imagen](https://user-images.githubusercontent.com/90937483/194164555-0b95962c-a60c-445a-8d21-74be4386278f.png)
