### ISSUE TITLE
El cuarto requerimiento no ha sido desbloqueado :(

### ISSUE THREAD

**Issue by gabobaxx** [midudev/password-generator#273]
![2022-10-06-173431_435x386_scrot](https://user-images.githubusercontent.com/59029788/194423064-f1d035ea-77c9-47a9-8f7a-6b291de99a05.png)

Ya se el problema pero ya me estaba ilusionado con el proyecto.

**Comment by leflores-fisi** [comment]
Cuál es el problema al que te refieres? No he podido estar atento a los streams :crying_cat_face:

**Comment by gabrielba15** [comment]
> Cuál es el problema al que te refieres? No he podido estar atento a los streams crying_cat_face

Los pull que se hagan a este repositorio ya no seran contados en el hacktoberfest porque segun ellos, este repo no cumple con los reglas.

**Comment by LcsGrz** [comment]
@midudev Se sabe algo de este concurso? en que quedo?
