### ISSUE TITLE
Lint errors

### ISSUE THREAD

**Issue by marsidev** [midudev/password-generator#49]
Hay muchos errores de `lint` en el código de los distintos participantes, seguramente algunos de ellos no tienen instalado la extensión de `eslint` y por eso no se dan cuenta. Aquí un ejemplo de uno de ellos:
![image](https://user-images.githubusercontent.com/56328053/193437935-3468627a-5fcc-4040-af82-421dbf964f7a.png)

Propongo lo siguiente:

- [x] Sugerir la extensión de `eslint` y `prettier` en `.vscode/extensions.json`
- [x] Agregar scripts `lint:fix` y `format`
- [x] Indicar en el readme o en la landing que deben formatear su código antes de hacer la PR, ejecutando los scripts `lint:fix` y `format`
  - Preferiblemente un comando personalizado como `npx eslint src/pages/entry/<user>/** src/components/<user>/**`
- [ ] Agregar un github actions para ejecutar estos scripts también al hacer PRs. Se puede usar el de la [miduconf](https://github.com/midudev/miduconf-website/blob/main/.github/workflows/ci.yml) como referencia
- [ ] No mergear PRs que no pasen el CI
- [ ] Agregar soporte de eslint a más frameworks ([svelte](https://www.npmjs.com/package/eslint-plugin-svelte), [vue](https://www.npmjs.com/package/eslint-plugin-vue)). Actualmente, el eslint solo está funcionando en archivos javascript, typescript, .jsx, .tsx y .astro

Por otro lado, intenté ejecutar `npx eslint .` para saber cuantos errores/warns había y obtuve este error 
```bash
RangeError: Maximum call stack size exceeded
Occurred while linting C:\...\hacktoberfest-2022\src\pages\entry\charlesvp15\index.astro:1
Rule: "indent"
```
No sé porqué sucede, pero el error desaparece al remover o minificar un pedazo de svg que hay en ese archivo.
Después de resolver el problema del svg y ejecutando el eslint otra vez, finalmente pude ver la cantidad de errores:
![image](https://user-images.githubusercontent.com/56328053/193439856-d95fe448-63f0-44ae-9c5a-2dd00b66f4f3.png)

**Comment by nilesh9836** [comment]
can you assign this issue to me ?
