### ISSUE TITLE
Override of the main background color

### ISSUE THREAD

**Issue by david-ponc** [midudev/password-generator#68]
With the latest changes, the background color of the home page was affected.

**Comment by marsidev** [comment]
Imagen de referencia
![image](https://user-images.githubusercontent.com/56328053/193463007-e1491038-0f43-429f-b98f-628fc8e441fe.png)

Para lograr que el background ocupe el 100% de la altura se puede agregar `height: fit-content;` al  `main`. Alternativamente, se puede añadir un scroll en la lista de participantes, ya que la lista puede llegar a ser demasiado larga.

**Comment by yogesh-9999** [comment]
hey @david-ponc please assign this task to me.

**Comment by david-ponc** [comment]
@yogesh-9999 I don't have the permissions to do that, just report the problem

**Comment by david-ponc** [comment]
Fixed problem by https://github.com/midudev/hacktoberfest-2022/commit/9654760e4956611c2d9a7082c36e751f4f76ed20

**Comment by david-ponc** [comment]
#131 please, using scoped styles on body to avoid override background color of home page

**Comment by maadeval** [comment]
Fixed, thanks! 😊
